# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_Main:
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(600, 445)
        self.setStyleSheet("QMainWindow {\n"
"    background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.617, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(194, 194, 194, 255));\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(8, 8, 8, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(28)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.usrName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.usrName.setFont(font)
        self.usrName.setObjectName("usrName")
        self.horizontalLayout_6.addWidget(self.usrName)
        self.outBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outBtn.setFont(font)
        self.outBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(182, 66, 66);\n"
"    border-radius: 2px\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid red;\n"
"    color: rgb(255, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(216, 0, 0);\n"
"    background-color: rgb(136, 49, 49);\n"
"}")
        self.outBtn.setObjectName("outBtn")
        self.horizontalLayout_6.addWidget(self.outBtn)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("QFrame {\n"
"    border-radius: 8px;\n"
"}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 584, 283))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vertLay = QtWidgets.QVBoxLayout()
        self.vertLay.setObjectName("vertLay")
        self.verticalLayout_3.addLayout(self.vertLay)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.newBtn = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.newBtn.setFont(font)
        self.newBtn.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(66, 66, 182);\n"
"    border-radius: 2px\n"
"}\n"
"QPushButton:hover {\n"
"    border: 1px solid blue;\n"
"    color: rgb(0, 0, 255);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:pressed {\n"
"    color: rgb(0, 216, 0);\n"
"    background-color: rgb(49, 49, 136);\n"
"}")
        self.newBtn.setObjectName("newBtn")
        self.verticalLayout.addWidget(self.newBtn)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveIcon = QtWidgets.QLabel(self.centralwidget)
        self.saveIcon.setPixmap(QPixmap('pic.png'))
        self.saveIcon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.saveIcon)
        self.lastSave = QtWidgets.QLabel(self.centralwidget)
        self.lastSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalLayout.addWidget(self.lastSave)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.aboutBtn = QtWidgets.QPushButton(self.centralwidget)
        self.aboutBtn.setObjectName("aboutBtn")
        self.horizontalLayout.addWidget(self.aboutBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Encrypted Notes"))
        self.label_11.setText(_translate("MainWindow", "Encrypted notes"))
        self.usrName.setText(_translate("MainWindow", "User"))
        self.outBtn.setText(_translate("MainWindow", "Выйти"))
        self.newBtn.setText(_translate("MainWindow", "Новая заметка"))
        self.lastSave.setText(_translate("MainWindow", "Последнее сохранение: никогда"))
        self.aboutBtn.setText(_translate("MainWindow", "О программе"))
